site_name: 自然语言处理学习笔记
site_url: https://nlp.gujiakai.top/
nav:
  - 绪论: index.md
  - 词汇分析与句法分析: 240319.md
  - 路路师姐分享: 240326.md
  - 语义分析与篇章分析: 240402.md
  - 语言模型: 240409.md
  - 信息抽取: 240416.md
  - 机器翻译: 240423.md
  - 情感分析: 240430.md
  - 智能问答: 240507.md
  - 文本摘要: 240514.md
  - 知识图谱: 240521.md
  - 模型稳健性: 240528.md
  - 模型可解释性: 240604.md